import { RegexEngine, Slex } from "@scinorandex/slex";
import { Result, Sparse } from "../index";
import { selfhosted } from "./states";
import { TableState } from "../parser";
import { GrammarToken, GrammarTokenMetadata, GrammarTokenType, hydrateProduction, Production } from "./common";

export const grammarLexerGenerator = new Slex<GrammarTokenType, GrammarTokenMetadata>({
  EOF_TYPE: GrammarTokenType.EOF,
  isHigherPrecedence: () => false,
  ignoreTokens: [GrammarTokenType.SINGLE_LINE_COMMENT, GrammarTokenType.MULTI_LINE_COMMENT],
});

grammarLexerGenerator.addRule(
  "lowercase",
  "a | b | c | d | e | f | g | h | i | j | k | l | m | n | o | p | q | r | s | t | u | v | w | x | y | z",
);
grammarLexerGenerator.addRule(
  "uppercase",
  "A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z",
);
grammarLexerGenerator.addRule("letter", "${lowercase} | ${uppercase}");
grammarLexerGenerator.addRule("digit", "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9");
grammarLexerGenerator.addRule("alphanumeric", "${letter} | ${digit}");
grammarLexerGenerator.addRule(
  "identifier",
  "(${letter} | $_) (${letter} | ${digit} | $_)*",
  GrammarTokenType.IDENTIFIER,
);
grammarLexerGenerator.addRule("colon", "$:", GrammarTokenType.COLON);
grammarLexerGenerator.addRule("semicolon", "$;", GrammarTokenType.SEMICOLON);
grammarLexerGenerator.addRule("langle", "$<", GrammarTokenType.L_ANGLE);
grammarLexerGenerator.addRule("rangle", "$>", GrammarTokenType.R_ANGLE);
grammarLexerGenerator.addRule("lbracket", "$[", GrammarTokenType.L_BRACKET);
grammarLexerGenerator.addRule("rbracket", "$]", GrammarTokenType.R_BRACKET);
grammarLexerGenerator.addRule("lparen", "$(", GrammarTokenType.L_PAREN);
grammarLexerGenerator.addRule("rparen", "$)", GrammarTokenType.R_PAREN);
grammarLexerGenerator.addRule("pipe", "$|", GrammarTokenType.PIPE);
grammarLexerGenerator.addRule("equals", "$=", GrammarTokenType.EQUALS);
grammarLexerGenerator.addRule("comma", "$,", GrammarTokenType.COMMA);
grammarLexerGenerator.addRule("question_mark", "$?", GrammarTokenType.QUESTION_MARK);
grammarLexerGenerator.addRule("star", "$*", GrammarTokenType.STAR);
grammarLexerGenerator.addRule("plus", "$+", GrammarTokenType.PLUS);
grammarLexerGenerator.addRule("number", "(${digit})+", GrammarTokenType.NUMBER);

grammarLexerGenerator.addRule("single_line_comment", "$/$/(($\n)!)*", GrammarTokenType.SINGLE_LINE_COMMENT);
grammarLexerGenerator.addRule("multi_line_comment", "$/$*(($*)!|($*($/)!))*$*$/", GrammarTokenType.MULTI_LINE_COMMENT);

export abstract class BaseNode {}

export class ListNode<T> extends BaseNode {
  private items: T[];

  constructor(items: T | T[]) {
    super();

    if (Array.isArray(items)) this.items = items;
    else this.items = [items];
  }

  add(item: T) {
    this.items.push(item);
    return this;
  }

  getItems() {
    return this.items;
  }

  getItemsReversed() {
    return this.items.toReversed();
  }
}

class ProductionNode extends BaseNode {
  constructor(
    public readonly lhs: GrammarToken,
    public readonly rhs: ListNode<TokenNode | GroupedTokenNode>,
    public originalProductionIndex: number,
    public readonly identifier: string,
    public readonly name?: string | undefined,
  ) {
    super();
  }

  fork(rhs: ListNode<TokenNode | GroupedTokenNode>) {
    return new ProductionNode(this.lhs, rhs, this.originalProductionIndex, this.identifier, this.name);
  }

  toStruct(): Production {
    if (this.originalProductionIndex === -1) throw new Error("ProductionNode has no originalProductionIndex");

    const hasGrouped = this.rhs.getItemsReversed().some((node) => node instanceof GroupedTokenNode);
    if (hasGrouped) throw new Error("Need to unroll before serializing");

    return {
      lhs: this.lhs,
      identifier: `<${this.identifier}>`,
      name: this.name ?? null,
      originalProductionIndex: this.originalProductionIndex,
      rhs: this.rhs.getItemsReversed().map((node) => (node as TokenNode).toStruct()),
    };
  }

  setOriginalProductionIndex(index: number) {
    this.originalProductionIndex = index;
  }
}

class ExpanderContext {
  current = 0;

  constructor(public currentProductionIndex: number) {}

  getNextProductionIndex() {
    return this.currentProductionIndex++;
  }

  getAutogeneratedId() {
    return `autogen-${this.current++}`;
  }
}

function expandProduction(production: ProductionNode, ctx: ExpanderContext): ProductionNode[] {
  const rhs = production.rhs.getItemsReversed();

  for (let i = 0; i < rhs.length; i++) {
    const item = rhs[i];

    const beforeItems = rhs.slice(0, i);
    const afterItems = rhs.slice(i + 1);

    if (item instanceof GroupedTokenNode) {
      // The unrolling rules here depend on the modifier in the GroupedTokenNode

      if (item.modifier === GrammarTokenType.QUESTION_MARK) {
        const withoutCurrentItem = production.fork(
          new ListNode<TokenNode | GroupedTokenNode>([...beforeItems, ...afterItems].toReversed()),
        );

        const withCurrentItem = production.fork(
          new ListNode<TokenNode | GroupedTokenNode>(
            [...beforeItems, ...item.inside.getItemsReversed(), ...afterItems].toReversed(),
          ),
        );

        const newProductions: ProductionNode[] = [withoutCurrentItem, withCurrentItem];
        return newProductions.flatMap((prod) => expandProduction(prod, ctx));
      } else if (item.modifier === GrammarTokenType.STAR || item.modifier === GrammarTokenType.PLUS) {
        // need to handle kleene-star and kleene-plus, which create entirely unique new productions
        const inside = item.inside.getItemsReversed();
        const newProductionIdentifier = ctx.getAutogeneratedId();

        // create a dummy production that contains the contents of inside
        const raw = new StubTokenNode("variable", new ListNode([production.lhs]), "rest", newProductionIdentifier);
        const pump = new GroupedTokenNode(new ListNode([raw]), GrammarTokenType.QUESTION_MARK);

        const stub = new ProductionNode(
          production.lhs,
          new ListNode<TokenNode | GroupedTokenNode>([...inside, pump].toReversed()),
          ctx.getNextProductionIndex(),
          newProductionIdentifier,
          "autogenerated-kleene", // the user needs to implement a reducer named "autogenerated-kleene"
        );

        const currentReplacement = production.fork(
          new ListNode(
            [...beforeItems, item.modifier === GrammarTokenType.STAR ? pump : raw, ...afterItems].toReversed(),
          ),
        );

        return [currentReplacement, stub].flatMap((prod) => expandProduction(prod, ctx));
      } else throw new Error(`Unknown modifier ${GrammarTokenType[item.modifier]}`);
    } else if (item instanceof TokenNode) {
      if (item.variables.getItems().length > 1) {
        // this token node has many variants and we should unroll it
        const variables = item.variables.getItemsReversed();

        const newProductions = variables.map((variable) => {
          return production.fork(
            new ListNode<TokenNode | GroupedTokenNode>(
              [
                ...beforeItems,
                new TokenNode(item.type, new ListNode<GrammarToken>([variable]), item.name),
                ...afterItems,
              ].toReversed(),
            ),
          );
        });

        return newProductions.flatMap((prod) => expandProduction(prod, ctx));
      }
    } else {
      throw new Error("shoudn't reach here, ProductionNode RHS is neither GroupedTokenNode nor TokenNode");
    }
  }

  // if it reached here then its normal
  return [production];
}

class TokenNode extends BaseNode {
  constructor(
    public readonly type: "terminal" | "variable",
    public readonly variables: ListNode<GrammarToken>,
    public readonly name: string | undefined,
  ) {
    super();
  }

  public getIdentifier() {
    const items = this.variables.getItems();
    if (items.length > 1) throw new Error("Not yet unrolled");
    return items[0].lexeme;
  }

  toStruct() {
    const items = this.variables.getItems();
    if (items.length > 1) throw new Error("Not yet unrolled");

    const lexeme = this.getIdentifier();
    const identifier = this.type === "variable" ? `<${lexeme}>` : `[${lexeme}]`;
    const name = this.name ?? null;

    return { type: this.type, token: items[0], identifier, name };
  }
}

class StubTokenNode extends TokenNode {
  constructor(
    public readonly type: "terminal" | "variable",
    public readonly variables: ListNode<GrammarToken>,
    public readonly name: string | undefined,
    public readonly identifier: string,
  ) {
    super(type, variables, name);
  }

  public getIdentifier() {
    return this.identifier;
  }
}

class GroupedTokenNode extends BaseNode {
  constructor(
    public readonly inside: ListNode<TokenNode>,
    public readonly modifier: GrammarTokenType,
  ) {
    super();
  }
}

class ProgramNode extends BaseNode {
  constructor(public readonly productions: ListNode<ProductionNode>) {
    super();
  }

  unrollProductions() {
    const productions = this.productions.getItemsReversed();
    const expanderContext = new ExpanderContext(this.productions.getItems().length);

    for (let i = 0; i < productions.length; i++) productions[i].setOriginalProductionIndex(i);
    return productions.flatMap((node) => expandProduction(node, expanderContext));
  }

  getProductions() {
    return this.unrollProductions().map((node) => node.toStruct());
  }
}

export function getSelfHostedParserGenerator(e: typeof selfhosted = selfhosted) {
  return new Sparse<GrammarTokenType, GrammarTokenMetadata, BaseNode>({
    productions: e.productions.map((production) => hydrateProduction(production as any)),
    states: e.states.map((state) => TableState.fromJSObject(state as any)),
    toStringifiedTokenType: (type: GrammarTokenType) => GrammarTokenType[type],
  });
}

type Reducer = (bag: any) => BaseNode;
const reducers: { [key: string]: Reducer } = {
  program: (bag: { productions?: ListNode<ProductionNode> }) =>
    new ProgramNode(bag.productions ?? new ListNode<ProductionNode>([])),

  productions: (bag: { production: ProductionNode; rest?: ListNode<ProductionNode> }) => {
    if (bag.rest == null) return new ListNode<ProductionNode>([bag.production]);
    else return bag.rest.add(bag.production);
  },

  production: (bag: {
    production_name: GrammarToken;
    tokens: ListNode<TokenNode | GroupedTokenNode>;
    uuid?: GrammarToken;
  }) => new ProductionNode(bag.production_name, bag.tokens, -1, bag.production_name.lexeme, bag.uuid?.lexeme),

  tokens: (bag: { token: TokenNode | GroupedTokenNode; rest?: ListNode<TokenNode | GroupedTokenNode> }) => {
    if (bag.rest == null) return new ListNode<TokenNode | GroupedTokenNode>([bag.token]);
    else return bag.rest.add(bag.token);
  },

  token: (bag: { token: TokenNode }) => bag.token,
  grouped_token: (bag: { tokens: ListNode<TokenNode>; modifier: GrammarToken }) =>
    new GroupedTokenNode(bag.tokens, bag.modifier.type),

  variable: (bag: { inside: ListNode<GrammarToken>; token_name?: GrammarToken }) =>
    new TokenNode("variable", bag.inside, bag.token_name?.lexeme),

  terminal: (bag: { inside: ListNode<GrammarToken>; token_name?: GrammarToken }) =>
    new TokenNode("terminal", bag.inside, bag.token_name?.lexeme),

  inside: (bag: { identifier: GrammarToken; rest?: ListNode<GrammarToken> }) => {
    if (bag.rest == null) return new ListNode<GrammarToken>([bag.identifier]);
    else return bag.rest.add(bag.identifier);
  },
};

export const tryBuildProductions = (lexer: LexerInterface | string): Result<Production[]> => {
  if (typeof lexer === "string") lexer = grammarLexerGenerator.generate(lexer, () => ({}));

  const parserGenerator = getSelfHostedParserGenerator();
  const parser = parserGenerator.generate(lexer as RegexEngine<GrammarTokenType, GrammarTokenMetadata>, {
    reducer: ({ bag, name }) => {
      return reducers[name ?? ""](bag);
    },
  });

  const parsingResult = parser.parse().result as ProgramNode;
  const productions = parsingResult.getProductions();
  return { success: true, value: productions };
};

interface LexerInterface {
  peekNextToken(): GrammarToken;
  getNextToken(): GrammarToken;
  hasNextToken(): boolean;
}

export const buildProductions = (lexer: LexerInterface | string): Production[] => {
  const result = tryBuildProductions(lexer);
  if (result.success === false)
    throw new Error(
      `Encountered error "${result.reason}" while parsing grammar at ${result.token.line}:${result.token.column}`,
    );
  return result.value;
};
