import { Slex, Token as SlexToken } from "@scinorandex/slex";
import { buildProductions, LR1StackSymbol, Sparse } from "../../src/index";
import fs from "fs/promises";

// prettier-ignore
enum TokenType {
  PLUS, MINUS, STAR, SLASH, NUMBER, EOF
}

type Metadata = {};
type Token = SlexToken<TokenType, Metadata>;

const lexerGenerator = new Slex<TokenType, Metadata>({
  EOF_TYPE: TokenType.EOF,
  isHigherPrecedence: ({ current, next }) => false,
});

lexerGenerator.addRule("plus", "$+", TokenType.PLUS);
lexerGenerator.addRule("minus", "$-", TokenType.MINUS);
lexerGenerator.addRule("star", "$*", TokenType.STAR);
lexerGenerator.addRule("forward_slash", "$/", TokenType.SLASH);
lexerGenerator.addRule("digit", "0|1|2|3|4|5|6|7|8|9");
lexerGenerator.addRule("float_number", "(${digit})+$.(${digit})+");
lexerGenerator.addRule("decimal_number", "(${digit})+");
lexerGenerator.addRule("number_literal", "${float_number}|${decimal_number}", TokenType.NUMBER);

const lexer = lexerGenerator.generate(`2.4 + 3.5 + 2`, () => ({}));

type StringifiedNode = (StringifiedNode | string)[];
class Node {
  constructor(public readonly nodes: LR1StackSymbol<TokenType, Metadata, Node>[]) {}
  toObject(): StringifiedNode {
    return this.nodes.map((node) => (node.type === "token" ? node.token.lexeme : node.node.toObject()));
  }
}

class KleeneNode<T> extends Node {
  contents: T[] = [];

  constructor(
    public readonly nodes: LR1StackSymbol<TokenType, Metadata, Node>[],
    bag: any,
  ) {
    super(nodes);
    this.contents.unshift(bag);
  }

  add(nodes: LR1StackSymbol<TokenType, Metadata, Node>[], bag: T) {
    this.nodes.unshift(...nodes.slice(0, nodes.length - 1));
    this.contents.unshift(bag);
    return this;
  }
}

type Reducer = (bag: any, input: LR1StackSymbol<TokenType, Metadata, Node>[]) => Node;
const reducers: { [key: string]: Reducer } = {
  "autogenerated-kleene": (bag, input) => {
    const { rest, ...otherNodes } = bag;
    if (rest == null) return new KleeneNode(input, otherNodes);
    else if (rest instanceof KleeneNode) return rest.add(input, otherNodes);
    // You should not be able to reach this because this function always returns a KleeneNode
    else throw new Error("Invalid reducer");
  },

  program: (bag: { first_number: Node; rest: KleeneNode<{ op: Token; extra_number: Token }> }, input) => {
    return new Node(input);
  },
};

async function main() {
  const toStringifiedTokenType = (type: TokenType) => TokenType[type];
  const productions = buildProductions(await fs.readFile("./example/kleene-test/grammar.txt", "utf8"));

  const parserGenerator = Sparse.fromProductions<TokenType, Metadata, Node>({ productions, toStringifiedTokenType });
  const parser = parserGenerator.generate(lexer, {
    reducer: ({ bag, name }, { input }) => {
      const reducer = reducers[name ?? ""];
      if (reducer == null) throw new Error(`No reducer for ${name}`);
      return reducer(bag, input);
    },
  });

  console.log(parser.parse().result!);
}

main();
