import { Slex, Token as SlexToken } from "@scinorandex/slex";
import {
  LR1StackSymbol,
  Sparse,
  assertReducersCoverGrammar,
  defineReducers,
  enumToString,
  loadGrammar,
} from "../../src/index";
import path from "path";

// prettier-ignore
enum TokenType {
  PLUS, MINUS, STAR, SLASH, NUMBER, EOF
}

type Metadata = {};
type Token = SlexToken<TokenType, Metadata>;

const lexerGenerator = new Slex<TokenType, Metadata>({
  EOF_TYPE: TokenType.EOF,
  isHigherPrecedence: ({ current, next }) => false,
});

lexerGenerator.addRule("plus", "$+", TokenType.PLUS);
lexerGenerator.addRule("minus", "$-", TokenType.MINUS);
lexerGenerator.addRule("star", "$*", TokenType.STAR);
lexerGenerator.addRule("forward_slash", "$/", TokenType.SLASH);
lexerGenerator.addRule("digit", "0|1|2|3|4|5|6|7|8|9");
lexerGenerator.addRule("float_number", "(${digit})+$.(${digit})+");
lexerGenerator.addRule("decimal_number", "(${digit})+");
lexerGenerator.addRule("number_literal", "${float_number}|${decimal_number}", TokenType.NUMBER);

const lexer = lexerGenerator.generate(`2.4 + 3.5 + 2`, () => ({}));

type StringifiedNode = (StringifiedNode | string)[];
class Node {
  constructor(public readonly nodes: LR1StackSymbol<TokenType, Metadata, Node>[]) {}
  toObject(): StringifiedNode {
    return this.nodes.map((node) => (node.type === "token" ? node.token.lexeme : node.node.toObject()));
  }
}

class KleeneNode<T> extends Node {
  contents: T[] = [];

  constructor(
    public readonly nodes: LR1StackSymbol<TokenType, Metadata, Node>[],
    bag: any,
  ) {
    super(nodes);
    this.contents.unshift(bag);
  }

  add(nodes: LR1StackSymbol<TokenType, Metadata, Node>[], bag: T) {
    this.nodes.unshift(...nodes.slice(0, nodes.length - 1));
    this.contents.unshift(bag);
    return this;
  }
}

// Every reducer receives (newInput, oldInput): newInput is { bag, name } (the bag holds the named
// symbols of the right hand side), oldInput is { input, index } (the raw symbols in order).
type Reducer = (
  newInput: { bag: any; name: string | null },
  oldInput: { input: LR1StackSymbol<TokenType, Metadata, Node>[]; index: number },
) => Node;

const reducers: Record<string, Reducer> = {
  // Every "*" and "+" group produces a list production named "autogenerated-kleene", which has to
  // flatten the list it is handed: the first reduction has no "rest", later ones do.
  "autogenerated-kleene": ({ bag }, { input }) => {
    const { rest, ...otherNodes } = bag;
    if (rest == null) return new KleeneNode(input, otherNodes);
    else if (rest instanceof KleeneNode) return rest.add(input, otherNodes);
    else throw new Error("Invalid reducer");
  },

  program: (_, { input }) => new Node(input),
};

const root = path.join(__dirname, "..", "..");

async function main() {
  const productionsResult = await loadGrammar(path.join(root, "example/kleene-test/grammar.txt"));
  if (productionsResult.success === false) throw new Error(productionsResult.reason);

  // Fails loudly here if a production in the grammar has no reducer, instead of halfway through a parse.
  assertReducersCoverGrammar(productionsResult.value, reducers);

  // No table file for this example, so the states are generated from the grammar at startup.
  const parserGenerator = Sparse.fromProductions<TokenType, Metadata, Node>({
    productions: productionsResult.value,
    toStringifiedTokenType: enumToString(TokenType),
  });

  const parser = parserGenerator.generate(lexer, {
    reducer: defineReducers(reducers),
  });

  console.log(parser.parse().result!);
}

main();
