import { Production } from "../meta/common";

export const KLEENE_REDUCER_NAME = "autogenerated-kleene";

/** The names of every production that has a `: name` in the grammar file. */
export const namedProductions = (productions: Production[]): string[] => {
  const names = new Set<string>();
  for (const production of productions)
    if (production.name != null) names.add(production.name);
  return [...names].sort();
};

/** Every named production in the grammar that `reducers` does not have a reducer for. */
export const missingReducerNames = (
  productions: Production[],
  reducers: Record<string, unknown>,
): string[] => namedProductions(productions).filter((name) => reducers[name] == null);

const describeKleene = (productions: Production[]) => {
  const needed = productions.filter(
    (production) =>
      production.name === KLEENE_REDUCER_NAME ||
      production.identifier.startsWith("<autogen-"),
  );
  if (needed.length === 0) return "";

  return `\nNote: this grammar uses "*" or "+", so it has ${needed.length} autogenerated list production(s) named "${KLEENE_REDUCER_NAME}". That reducer has to flatten the list it is handed (see README, "Repetition with * and +").`;
};

export const missingReducerMessage = (
  productions: Production[],
  reducers: Record<string, unknown>,
): string => {
  const missing = missingReducerNames(productions, reducers);
  if (missing.length === 0) return "";

  const has = namedProductions(productions).filter((name) => reducers[name] != null);
  const kleene = missing.includes(KLEENE_REDUCER_NAME) ? describeKleene(productions) : "";

  return (
    `No reducer for ${missing.length === 1 ? "production" : "productions"} ${missing
      .map((name) => `"${name}"`)
      .join(", ")}.` +
    `\nReducers are keyed by the name given in the grammar, e.g. "<PROGRAM: program>" is reduced by reducers.program.` +
    (has.length === 0 ? "\nYour reducer map is empty." : `\nYou have reducers for: ${has.join(", ")}.`) +
    kleene
  );
};

export type ReducerMap<Node> = Record<string, (newInput: any, oldInput: any) => Node>;

/**
 * Wraps a map of reducers into the single reducer that `Sparse.generate` expects, keyed by the
 * `: name` of each production in the grammar.
 *
 * A missing entry is reported by production name instead of surfacing as
 * `reducers[name] is not a function` from deep inside the parse.
 */
export const defineReducers = <Reducers extends Record<string, (...args: never[]) => unknown>>(reducers: Reducers) =>
  function sparseReducer(newInput: any, oldInput: any): any {
    const name: string | null | undefined = newInput?.name;
    const lookup = reducers as unknown as Record<string, (a: any, b: any) => any>;
    const reducer = name == null ? undefined : lookup[name];
    if (reducer == null)
      throw new Error(
        `No reducer for production "${name ?? ""}" (production ${oldInput?.index}). Reducers are keyed by the name given in the grammar.`,
      );
    return reducer(newInput, oldInput);
  };

/**
 * Throws a descriptive error if `reducers` is missing any production the grammar names.
 * Useful as a one-time check right after loading the grammar.
 */
export const assertReducersCoverGrammar = (productions: Production[], reducers: ReducerMap<unknown>) => {
  const message = missingReducerMessage(productions, reducers);
  if (message !== "") throw new Error(message);
};

/**
 * The stringifier every example used to write by hand: `(type) => TokenType[type]`.
 * Numeric TypeScript enums store their names in reverse, so a plain lookup is all it takes.
 *
 * ```ts
 * const toStringifiedTokenType = enumToString<TokenType>(TokenType);
 * ```
 */
export const enumToString =
  <TokenType = unknown>(tokenTypes: object) =>
  (tokenType: TokenType): string => {
    const name = (tokenTypes as Record<string, unknown>)[tokenType as unknown as string];
    return `${name ?? tokenType}`;
  };
